/**
 * Arborescence des catégories et sous-catégories
 * Basée sur l'ancien site PrestaShop
 */
export const CATEGORY_TREE = {
  'Agroalimentaire': [
    'Masques & protection',
  ],
  'American style': [
    'Ardoise',
    'Ensemble pierre chaud',
  ],
  'Armoire orangina': [],
  'Article de fête': [
    'Boule géant led',
    'Étoile géante',
    'Paille lumineuse',
    'Pom pom papier',
    'Ruban',
    'Sacs de jute',
  ],
  'Arts de table': [
    'Amuses-bouche porcelaine',
    'Casier transport verrerie',
    'Couverts de table',
    'Gobelets réutilisables',
    'Mini cocotte',
    'Plat escargot',
    'Plat porcelaine',
    'Saladier ramequin bol',
    'Tasses',
    'Vaisselles émaillées',
    'Verrerie',
  ],
  'Batterie de cuisine': [
    'Autocuiseur',
    'Bain-marie inox',
    'Bassines inox',
    'Batterie aluminium',
    'Batterie fonte aluminium',
    'Batterie fonte',
    'Casseroles',
    'Couscoussier',
    'Marmite inox',
    'Paella',
    'Poêle inox',
    'Wok',
  ],
  'Boucherie / Traiteur': [
    'Affûteuses à couteaux',
    'Aiguilles à brider',
    'Armoires de maturation',
    'Attendrisseurs à viande',
    'Coupe-légumes',
    'Couteaux',
    'Cutters de table',
    'Fumoir',
    'Hachoirs',
    'Lames de scie',
    'Machines sous-vide',
    'Mélangeur à viande',
    'Plateaux inox',
    'Poussoirs à saucisses',
    'Press hamburger',
    'Scelleuses',
    'Scie à os',
    'Trancheuses',
  ],
  'Boulangerie': [
    'Accessoires boulangerie',
    'Armoire pâtisserie',
    'Armoires de fermentation',
    'Batteur mélangeur',
    'Coupeuse à pain',
    'Diviseuse / Façonneuse',
    'Four',
    'Laminoir',
    'Moules & plaques',
    'Pétrin',
  ],
  'Buanderie': [],
  'Caisses, balances et autre': [],
  'Caisson transport': [],
  'Cuisson': [
    'Fours professionnels',
    'Friteuses',
    'Grills & Plancha',
    'Induction',
    'Plaques de cuisson',
    'Salamandres',
    'Taque de cuisson',
  ],
  'Echelle Chariot Diable': [],
  'Figurine en plâtre': [],
  'Forain & Crêperie': [
    'Accessoires crêperie',
    'Appareil à donuts',
    'Barbe à papa',
    'Chariot à crêpes',
    'Crêpières électriques',
    'Crêpières Gaz',
    'Distributeurs de boissons',
    'Friteuses à Beignets',
    'Gaufriers',
    'Machine à churros',
    'Machine à granité',
    'Machine à poffertjes',
    'Pop corn',
    'Press à tartelette',
    'Sirop à granité',
  ],
  'Glacier': [],
  'Hôtel': [],
  'Hygiène': [],
  'Inox': [
    'Armoires hautes inox',
    'Armoire murale inox',
    'Étagères chef',
    'Étagères inox',
    'Grilles pâtissières / gastro',
    'Plonges',
    'Poubelles inox',
    'Tables sur armoire',
    'Tables de travail',
  ],
  'Jetable': [],
  'Kebab': [
    'Accessoires kebab',
    'Couteaux gyros électriques',
    'Gyros électrique',
    'Gyros gaz',
  ],
  'Lavage': [],
  'Linge de table': [],
  'Matériels de Préparations': [],
  'Menus stop trottoir Piques': [],
  'Mobilier': [],
  'Occasion': [],
  'Pièces détachées': [],
  'Pizzeria': [],
  'Plat au four inox': [],
  'Poissonnerie': [
    'Fabrique de glaçon',
    'Fruits de mer',
    'Plateau fruits de mer',
    'Vitrine réfrigérée',
  ],
  'Réfrigération & Congélation': [],
  'Remorque': [],
  'Rotissoires': [],
  'Self service chaud ou froid': [],
  'Snack': [],
  'Thermomètres': [],
  'Ustensiles de cuisine': [],
  'Ventilations': [],
  'Vêtement, chaussure et jetable': [],
  'Vitrine Plexiglas/verre': [],
  'Vitrines Chauffantes': [],
};

/** Liste plate des catégories principales (pour rétrocompatibilité) */
export const CATEGORIES = ['Toutes', ...Object.keys(CATEGORY_TREE)];
