export const CATEGORIES = [
  'Toutes', // Always keep "Toutes" at the top for the Catalogue filter
  'Agroalimentaire',
  'American style',
  'Armoire orangina',
  'Article de fête',
  'Arts de table',
  'Batterie de cuisine',
  'Boucherie / Traiteur',
  'Boulangerie',
  'Buanderie',
  'Caisses, balances et autre',
  'Caisson transport',
  'Cuisson',
  'Echelle Chariot Diable',
  'Figurine en plâtre',
  'Forain & Crêperie',
  'Glacier',
  'Hôtel',
  'Hygiène',
  'Inox',
  'Jetable',
  'Kebab',
  'Lavage',
  'Linge de table',
  'Matériels de Préparations',
  'Menus stop trottoir Piques',
  'Mobilier',
  'Occasion',
  'Pièces détachées',
  'Pizzeria',
  'Plat au four inox',
  'Poissonnerie',
  'Réfrigération & Congélation',
  'Remorque',
  'Rotissoires',
  'Self service chaud ou froid',
  'Snack',
  'Thermomètres',
  'Ustensiles de cuisine',
  'Ventilations',
  'Vêtement, chaussure et jetable',
  'Vitrine Plexiglas/verre',
  'Vitrines Chauffantes'
];
